name: pre-merge

on:
  pull_request:
    branches:
      - main
    paths:
      - "flake.nix"
      - "flake.lock"
      - "checks/**"
      - "packages/**"
      - "shell.nix"
      - ".github/workflows/checks.yml"
      - ".github/workflows/pre-merge.yml"

concurrency:
  group: pre-merge-checks
  cancel-in-progress: true

jobs:
  flake:
    uses: ./.github/workflows/checks.yml
